### ISSUE TITLE
Generic typed syntax highlighting is not always correct with <>

### ISSUE THREAD

**Issue by nathansizemore** [zargony/atom-language-rust#39]
<img width="456" alt="screen shot 2015-07-15 at 3 28 02 pm" src="https://cloud.githubusercontent.com/assets/3423825/8707875/6a9feb2e-2b06-11e5-8c63-01b72f424c57.png">

**Comment by nathansizemore** [comment]
<img width="444" alt="screen shot 2015-07-15 at 5 36 41 pm" src="https://cloud.githubusercontent.com/assets/3423825/8710487/2337bafc-2b18-11e5-94a1-8f6c8f0b68bd.png">

**Comment by zargony** [comment]
Thanks for reporting. This looks like the same bug reported in #33 and should be fixed in #37.

**Comment by nathansizemore** [comment]
Still not correct with latest update. 
Sender brackets are always white, while Receiver brackets are highlighted?
@zargony 

<img width="511" alt="screen shot 2015-07-23 at 4 26 33 pm" src="https://cloud.githubusercontent.com/assets/3423825/8861306/a35b4fba-3157-11e5-8526-08e7afcb5a04.png">
